blacklist:
  - ACACIA_BUTTON
  - ACACIA_PRESSURE_PLATE
  - ACACIA_SAPLING
  - ACACIA_SIGN
  - ACACIA_STAIRS
  - ACTIVATOR_RAIL
  - ALLIUM
  - AZURE_BLUET
  - BAMBOO
  - BARRIER
  - BEACON
  - BEDROCK
  - BELL
  - BIRCH_BUTTON
  - BIRCH_PRESSURE_PLATE
  - BIRCH_SAPLING
  - BIRCH_SIGN
  - BLACK_BANNER
  - BLACK_BED
  - BLACK_SHULKER_BOX
  - BLUE_BANNER
  - BLUE_BED
  - BLUE_CONCRETE_POWDER
  - BLUE_ORCHID
  - BLUE_SHULKER_BOX
  - BRAIN_CORAL_BLOCK
  - BRAIN_CORAL_FAN
  - BROWN_BANNER
  - BROWN_BED
  - BROWN_CONCRETE_POWDER
  - BROWN_MUSHROOM
  - BROWN_SHULKER_BOX
  - BUBBLE_CORAL
  - BUBBLE_CORAL_BLOCK
  - BUBBLE_CORAL_FAN
  - CACTUS
  - CAKE
  - CARVED_PUMPKIN
  - CHAIN_COMMAND_BLOCK
  - CHIPPED_ANVIL
  - CHORUS_FLOWER
  - CHORUS_PLANT
  - COMMAND_BLOCK
  - COMPARATOR
  - CONDUIT
  - CORNFLOWER
  - CYAN_BANNER
  - CYAN_BED
  - CYAN_CONCRETE_POWDER
  - CYAN_SHULKER_BOX
  - DAMAGED_ANVIL
  - DANDELION
  - DARK_OAK_BUTTON
  - DARK_OAK_DOOR
  - DARK_OAK_LEAVES
  - DARK_OAK_PRESSURE_PLATE
  - DARK_OAK_SAPLING
  - DARK_OAK_SIGN
  - DAYLIGHT_DETECTOR
  - DEAD_BRAIN_CORAL
  - DEAD_BRAIN_CORAL_FAN
  - DEAD_BUBBLE_CORAL
  - DEAD_BUBBLE_CORAL_BLOCK
  - DEAD_BUBBLE_CORAL_FAN
  - DEAD_BUSH
  - DEAD_FIRE_CORAL
  - DEAD_FIRE_CORAL_BLOCK
  - DEAD_FIRE_CORAL_FAN
  - DEAD_HORN_CORAL
  - DEAD_HORN_CORAL_BLOCK
  - DEAD_HORN_CORAL_FAN
  - DEAD_TUBE_CORAL
  - DEAD_TUBE_CORAL_BLOCK
  - DEAD_TUBE_CORAL_FAN
  - DETECTOR_RAIL
  - DRAGON_EGG
  - DRAGON_HEAD
  - END_PORTAL_FRAME
  - FERN
  - FIRE_CORAL
  - FIRE_CORAL_BLOCK
  - FIRE_CORAL_FAN
  - FLETCHING_TABLE
  - GRAY_BANNER
  - GRAY_BED
  - GRAY_CONCRETE_POWDER
  - GRAY_SHULKER_BOX
  - GREEN_BANNER
  - GREEN_BED
  - GREEN_CONCRETE_POWDER
  - GREEN_SHULKER_BOX
  - HEAVY_WEIGHTED_PRESSURE_PLATE
  - HOPPER
  - HORN_CORAL
  - HORN_CORAL_BLOCK
  - HORN_CORAL_FAN
  - INFESTED_CHISELED_STONE_BRICKS
  - INFESTED_COBBLESTONE
  - INFESTED_CRACKED_STONE_BRICKS
  - INFESTED_MOSSY_STONE_BRICKS
  - INFESTED_STONE
  - INFESTED_STONE_BRICKS
  - JIGSAW
  - JUNGLE_BUTTON
  - JUNGLE_PRESSURE_PLATE
  - JUNGLE_SAPLING
  - JUNGLE_SIGN
  - KELP
  - LIGHT_BLUE_BANNER
  - LIGHT_BLUE_BED
  - LIGHT_BLUE_CONCRETE_POWDER
  - LIGHT_BLUE_SHULKER_BOX
  - LIGHT_GRAY_BANNER
  - LIGHT_GRAY_BED
  - LIGHT_GRAY_CONCRETE_POWDER
  - LIGHT_GRAY_SHULKER_BOX
  - LIGHT_GRAY_TERRACOTTA
  - LIGHT_WEIGHTED_PRESSURE_PLATE
  - LILY_PAD
  - LIME_BANNER
  - LIME_BED
  - LIME_CONCRETE_POWDER
  - LIME_SHULKER_BOX
  - MAGENTA_BANNER
  - MAGENTA_BED
  - MAGENTA_CONCRETE_POWDER
  - MAGENTA_SHULKER_BOX
  - MOSSY_COBBLESTONE
  - NOTE_BLOCK
  - OAK_BUTTON
  - OAK_PRESSURE_PLATE
  - OAK_SAPLING
  - OAK_SIGN
  - ORANGE_BANNER
  - ORANGE_BED
  - ORANGE_CONCRETE_POWDER
  - ORANGE_SHULKER_BOX
  - OXEYE_DAISY
  - PEONY
  - PETRIFIED_OAK_SLAB
  - PINK_BANNER
  - PINK_BED
  - PINK_CONCRETE_POWDER
  - PINK_SHULKER_BOX
  - PINK_TULIP
  - PISTON
  - PLAYER_HEAD
  - PODZOL
  - POPPY
  - POWERED_RAIL
  - PURPLE_BANNER
  - PURPLE_BED
  - PURPLE_CONCRETE_POWDER
  - PURPLE_SHULKER_BOX
  - RAIL
  - REDSTONE_ORE
  - REDSTONE_TORCH
  - RED_BANNER
  - RED_BED
  - RED_CONCRETE_POWDER
  - RED_MUSHROOM
  - RED_SHULKER_BOX
  - RED_TULIP
  - REPEATER
  - REPEATING_COMMAND_BLOCK
  - ROSE_BUSH
  - SCAFFOLDING
  - SEAGRASS
  - SHULKER_BOX
  - SNOW
  - SPAWNER
  - SPRUCE_BUTTON
  - SPRUCE_PRESSURE_PLATE
  - SPRUCE_SAPLING
  - SPRUCE_SIGN
  - STICKY_PISTON
  - STONE_BUTTON
  - STRUCTURE_BLOCK
  - STRUCTURE_VOID
  - SUGAR_CANE
  - SUNFLOWER
  - TALL_GRASS
  - TNT
  - TRAPPED_CHEST
  - TRIPWIRE_HOOK
  - TUBE_CORAL
  - TUBE_CORAL_BLOCK
  - TUBE_CORAL_FAN
  - TURTLE_EGG
  - VINE
  - WET_SPONGE
  - WHEAT
  - WHITE_BANNER
  - WHITE_BED
  - WHITE_CONCRETE_POWDER
  - WHITE_SHULKER_BOX
  - WHITE_TULIP
  - WITHER_ROSE
  - WITHER_SKELETON_SKULL
  - YELLOW_BANNER
  - YELLOW_BED
  - YELLOW_CONCRETE_POWDER
  - YELLOW_GLAZED_TERRACOTTA
  - YELLOW_SHULKER_BOX
  - YELLOW_TERRACOTTA
  - ZOMBIE_HEAD