name: SingleMaterial
version: @project.version@
author: Jim (NotKatuen)
description: Restricts players to bulding with a single material

main: uk.co.notnull.SingleMaterial.SingleMaterial
api-version: 1.17